baseurl = "http://dustinmm80.github.io/bostondevops_org/"
languageCode = "en-us"
title = "bostondevops.org"
theme = "landing-page-hugo"
canonifyurls: true

[params]
  description = "Home of the Boston DevOps Meetup"

[[params.social]]
  title = "meetup"
  icon = "users"
  url = "http://www.meetup.com/Boston-Devops/"

[[params.social]]
  title = "slack"
  icon = "slack"
  url = "https://bostondevops-invites.herokuapp.com/"

[[params.social]]
  title = "twitter"
  icon = "twitter"
  url = "https://twitter.com/BostonDevops"